README.md
tests/test_SuperwidgetEvents.js
tests/test_SuperwidgetUI.js
tests/test_YesGraphAPI.js
tests/tests.html
yesgraph-invites.css
yesgraph-invites.js
yesgraph.js

Allows customers to turn off specific parts of the Superwidget. In most cases this will be used by customers who only want the contact importer, and not the email sending, social share buttons, etc.
We've been talking with customers who already have a referral program, but would want to add our contact importer to the mix. This allows them to turn off everything but the contact importer.
Start with the changes to the `configureAPI()` method in `yesgraph.js`.
Open `tests/test.html` in the browser! I've added some tests with QUnit.
https://app.asana.com/0/77757700101210/131194538241617
https://app.asana.com/0/77757700101210/119313227805276
Yes. I'll update docs.yesgraph.com
No

Partial widget

---

gulptools/config.js
gulptools/tasks/compile.js
gulptools/tasks/deploy.js
gulptools/tasks/minify.js
gulptools/tasks/test.js
gulptools/tasks/update.js
gulptools/tasks/watch.js
karma.conf.js
package.json
src/demo_widget.html
src/dev/yesgraph-invites.js
src/dev/yesgraph-invites.less
src/dev/yesgraph.js
src/yesgraph-invites.js
src/yesgraph-invites.less
src/yesgraph.js
tests/test_api.js
tests/test_superwidget.js

- Fixes a bug in the deploy process, where minified versions weren't deploying.
- Adds testing to the deploy process
- Adds [gulp-autoprefixer](https://www.npmjs.com/package/gulp-autoprefixer) to the build process
- Automatically adds prefixes (`-webkit-`, `-moz-`, etc.) to our css files, to make the styling more consistent across browsers.
- Adds sourcemaps for the minified javascript files.
- It's difficult to debug Sentry errors when the traceback shows only minified code. With the new sourcemaps, Sentry should be able to automatically show tracebacks with _unminified_ code.
- Logs "breadcrumbs" to Sentry
- These "breadcrumbs" will show up in Sentry error tracebacks, which should help us understand the sequence of events leading up to each error.
- Fixes a bug in the SDK, so that it …

Misc updates

---

package.json
src/dev/yesgraph-invites.js
src/dev/yesgraph-invites.less
src/yesgraph-invites.js
src/yesgraph-invites.less

- Adds Slack as a contact importing source
- Condenses the oauth code for various services into a single `AuthManager` constructor.
- We're adding Slack because a few companies want a team onboarding flow.
- I refactored the auth code into a single constructor because it was getting messy and hard to maintain. Now, adding a new contact importer won't require so much copying and pasting.
The new `AuthManager` constructor in src/dev/yesgraph-invites.js ([click here](https://github.com/YesGraph/yesgraph-superwidget/compare/slack_importing?expand=1#diff-6d2a12d760bbd72a115bede316ba4e18R1038) to jump to it)
- Run `gulp test`
- Here's how to try importing your contacts from slack:
- Run the api server locally, and update your local superwidget options by running this command in …

Slack Contact Importing

---

src/dev/yesgraph-invites.js
src/yesgraph-invites.js

Fixes a bug that was occurring in minified versions of the code, such that the auth flow would fail preemptively with the message "Gmail Authorization Failed".
- Run `gulp` (this will create the most recent minified version)
- In src/demo_widget.html, update line 18 to use the minified code (dev/yesgraph-invites.**min**.js)
- Run `npm start`, then import your contacts from http://localhost:8000/src/demo_widget.html
https://app.asana.com/0/59202558034519/155830436735737

Fix auth error in minified code

---

karma-jquery1.7.conf.js
karma.conf.js
src/dev/yesgraph.js
tests/test_api.js
tests/test_superwidget.js

Refactors the Raven dependency to (1) fail gracefully if it gets blocked by an ad-blocker, and (2) be more testable.
Previously, the `YesGraphAPI.install()` method would only set `YesGraphAPI.isReady = true` once Raven successfully loaded. However, certain ad-blockers will prevent Raven from loading. In that case we should log an analytics event but still complete the installation.
I've updated the tests to address these changes, so you can just run `npm test` 🙂
- [Refactor highly nested Superwidget code](https://app.asana.com/0/59202558034519/162364139954353)
- [Refactor Raven dependency to handle ad blockers](https://app.asana.com/0/59202558034519/162814167478518)

Refactor raven dependency to fail gracefully; Add tests

---

karma-jquery1.7.conf.js
karma.conf.js
src/dev/yesgraph-invites.js
tests/test_superwidget.js

Refactors the Clipboard.js dependency, so that the rest of the widget configuration doesn't need to wait for it to finish.
Previously we were waiting to load Clipboard.js before doing the rest of the widget setup, but since the only thing depending on it is the invite link section, we should be loading the script asynchronously and not blocking the rest of the setup.
Here's a flowchart of the original code structure:
It looks like a lot of changes, but actually most of it is just indentation changes. I copied the relevant changes into [this gist](https://gist.github.com/carolynjoneslee/1c3e6cef30ace8dc3e9b69ea9c1fca5f), so that's a good place to start.
Check out `YesGraphAPI.utils.loadClipboard` and `YesGraphAPI.utils.configureClipboard` (~line 1340 in src/dev/yesgraph-invites.js).
I've …

Refactor clipboard

---

package.json
src/dev/yesgraph-invites.js
src/dev/yesgraph.js
tests/test_api.js
tests/test_superwidget.js

Enables the SDK/Superwidget to retry certain failed ajax requests a finite number of times
There seems to be an issue on the API side where we sometimes don't return a response. Until that issue is fixed, we can improve the end user experience by ensuring that if certain key requests fail (e.g., for the client token, or the app settings), that it tries again before failing.
Start by reviewing the new `AjaxRetry` constructor [here](https://github.com/YesGraph/yesgraph-superwidget/pull/29/files#diff-1533003f6889d8c764c0e592f5d703f4R412), and then look at the changes to the `hitAPI` method [here](https://github.com/YesGraph/yesgraph-superwidget/pull/29/files#diff-1533003f6889d8c764c0e592f5d703f4L115).
No, but we should fix that underlying error with empty API responses returning status code …

Retry certain failed ajax requests

---

gulp/config.js
gulp/tasks/watch.js
karma-jquery1.7.conf.js
karma-sauce.conf.js
karma.conf.js
package.json
src/dev/yesgraph-invites.js
tests/test_api.js
tests/test_superwidget.js

This PR updates the way that the Superwidget completes the auth flow, so that it can be used on pages with dynamically generated urls (e.g., [user1.mywebsite.com](#), [user2.mywebsite.com](#), ...).
The basic auth flow is like this:
1. Superwidget opens a popup with the auth screen
2. The providor authorizes the user, and the redirects the popup to a specified "redirect url".
3. The Superwidget waits for the popup url to match the expected redirect url, and at that point it gets the access token from the url hash.
But if you want to have the Superwidget on a page with a dynamically generated url, you quickly run into a problem. The auth providors don't support pattern matching in redirect urls (e.g., [*.mywebsite.com](#)).
To get around that, we have to set the redirect url to a page with …

Handle redirect proxies in the auth popup

---

package.json
src/dev/yesgraph-invites.js
tests/test_superwidget.js

Previously to enter multiple emails in the superwidget, they had to be separated by commas. Now they can be separated by commas or whitespace.
Run `gulp test`
[Accept whitespace or commas as Superwidget email delimiters](https://app.asana.com/0/59202558034519/174289037462813)
No, but we should notify Alireza when this goes live.

Allow whitespace as a delimiter between multiple emails

---

demo_widget.html
src/dev/yesgraph-invites.js

This PR fixes a bug appearing in Chrome on the iPhone 6, whereby the oauth flow never fully finishes.
Users could go through the authorization parts, but the Superwidget failed to retrieve the resulting data & close the window. This is because Chrome doesn't support "popups", and it considers a window opened by `window.open(url, title)` to be a popup if and only if the `title` parameter is not "_blank". Because we were using "Google Authorization" as the title, it was considered a popup and it's value was `undefined`. Switching the title to "_blank" resolved the issue.
[This StackOverflow question](http://stackoverflow.com/a/30226002/6513736) lead me to the answer, referencing [this Chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=136610#c68).
To reproduce the …

Fix oauth bug (only in Chrome on iPhone 6)

---

gulp/config.js
gulp/tasks/build.js
gulp/tasks/compile.js
gulp/tasks/deploy.js
gulp/tasks/minify.js
gulp/tasks/version.js
package.json

This PR fixes a bug in the deploy process. Here's how it's supposed to work:
1. src/\*.less files get compiled & moved to dist/\*.css
2. src/\*.js files and dist/\*.css files get versioned & moved to dist/\*.js and dist/\*.css
3. dist/\* files get minified and copied into dist/\*.min.\*
4. dist/* gets deployed to the CDN (or to the deployed/ folder, if the `--test` param is used)
Previously, versioned files were ending up in src/ (not dist/).
Also, this PR uses gulp-debug to log filenames to the terminal while they're being processed. This is helpful because we can make sure the right files are being processed in the right order.
From the master branch, run `gulp deploy --test` Then run `git status`, and you'll notice that the files in src/ have been changed. That's bad!
From this branch, …

Bugfix in the deploy process

---

gulp/config.js
gulp/tasks/watch.js
src/dev/yesgraph-invites.js
tests/test_superwidget.js

Previously the Superwidget could parse emails separated by whitespace or punctuation:
```
some@email.com; some+other@email.com
some+third@email.com
```
But not emails  copied & pasted directly from Gmail, which come in this format:
```
Some Name <some@email.com>
```
This PR makes email parsing more robust, so we can handle that format, or a combination of formats:
```
some@email.com;
Carolyn Lee <carolyn@yesgraph.com> some+other@email.com
```
I've also made a small change to the gulp "watch" task, which makes development easier, but is never run in production.
Start with the changes in src/dev/yesgraph-invites.js
I've updated the tests, so just run `gulp test`
[Asana Task: Parse names & emails copied from Gmail](https://app.asana.com/0/59202558034519/186268521780747)

Enable parsing emails & names copied from Gmail

---

demo_widget.html
src/dev/yesgraph-invites.js
tests/test_superwidget.js

- Makes our error handling on the OAuth flow more robust, so that we can properly handle different errors in different browsers.
- Adds tests for the actual OAuth flow! 🎉
- Adds a DOM event ("completed.yesgraph.oauth") when the auth popup finishes, before contacts are imported.
When we open the auth popup, if an error occurs, we want to close the popup and show an error message. However, there are certain whitelisted errors that we should instead catch and ignore. 
We whitelist errors by checking them against a regex pattern, but the pattern was failing to catch some errors in certain browsers, because the error messages vary slightly. This change makes the regex pattern more general, so that we can handle greater variation in the error messages.
Also, whenever an error _doesn't_ get …

Error handling

---

src/dev/yesgraph-invites.js

Passes the `promote-matching-domains` flag from the HTML to the API when ranking contacts

Bugfix on promote-matching-domains

---

src/dev/yesgraph-invites.js

Jsonifies the ranking settings before we hit the /oauth endpoint, so they can be parsed as JSON server side
[WIP]

jsonify settings before hitting the api

---

src/dev/modules/controller.js

This PR fixes a bug for customers who aren't using our email backend.
This bug surfaced in the wake of a pretty big refactor. It was caused by an `if`/`else` block that wasn't copied over properly.
We should prevent this going forward by updating our tests to cover more configurations of dashboard settings.
src/dev/modules/controller.js
No
- Create a new app, but _don't_ configure any options for it.
- In the demo_widget.html file, replace the `<span>` & `<script>` tags with this code snippet:
```html
<script class="yesgraph-invites"
data-app="[YOUR APP ID]" data-contact-importing="false"
data-email-sending="false" data-invite-link="false" data-share-btns="false"
data-nolog="true" defer="" id="yesgraph" src="dist/dev/yesgraph-invites.min.js"><div class="yes-widget-container"><div …
```

Only validate settings for apps using our email backend

---

demo_auth.html
src/dev/modules/api.js
src/dev/modules/model.js
src/dev/modules/options.js
src/dev/modules/view.js

- Adds a client key validation step to the Superwidget, so that developers don't need to specify an `app_name` or an `invite_link` when the widget is initialized with a `client_key`.
- It also fixes a bug whereby the text on the "send" button in the contacts modal didn't change if we clicked "select all"
- It also changes the contacts modal UI so that clicking anywhere on the row (not just directly on the checkbox) selects the contact.
Start with the changes in src/dev/modules/api.js
Yes, see [this PR](https://github.com/YesGraph/api.yesgraph.com/pull/766).
Run `npm test`.
It can also be tested by loading the widget with a client key:
1. Create a client key. More on that [here](#).
2. Update demo_auth.html to include your client key
3. Run `npm start` to boot up the server, then load the …

Client key validation

---

demo_widget.html
src/dev/modules/model.js
src/dev/modules/options.js

Fixes a bug on the Address Book page where we would sometimes use bad superwidget options, and sets the stage for us to allow our users to have multiple superwidget options to select from.
Create a new project locally, then get it's app name and replace it everywhere this pr has [APPNAME]. 
Run this on your local db to get the superwidget options, options_id=0 has no share options, options_id=1 has share options. 
`INSERT INTO "superwidget_options"("id","app_name","saved_at","share_btns","tweet_msg","fb_app_id","url_to_share","gg_client_id","gg_redirect_url","email_invite_html","email_invite_subject","sg_api_key","contacts_modal_header","manual_input_send_button","widget_headline","default_sender_email","contact_import_btn_cta","email_service_provider","iterable_api_key","iterable_campaign …

added data param to select option set

---

gulp/config.js
gulp/tasks/build.js
gulp/tasks/consts.js
gulp/tasks/version.js
gulp/tasks/watch.js
package.json
src/dev/modules/api.js
src/dev/modules/consts.js
src/dev/modules/model.js
tests/test_api.js

- Changes the way we detect a local dev environment
- Previously we had a hacky way of checking the URL and the title of the page. Now we're defining it in the build process instead.
- Includes the `user_id` when we hit the /suggested-seen endpoint with a clientKey
- The `user_id` is optional with a ClientToken, but required with a ClientKey.
It's easiest to understand what's going on by trying it, so I'd suggest doing the tests first and then looking at package.json & gulp/tasks/consts.js
Nope
**Testing /suggested-seen:**
I've added an automated test for this, so you can just run `npm test`
**Testing Build Changes**
1. Run `npm start`.
2. From the "Network" tab in the console, you should see that the Superwidget is accessing the local version of the API:
3. Then kill the server and …

Suggested seen

---

demo_widget.html
src/dev/modules/api.js
src/dev/modules/consts.js
src/dev/modules/view.js
tests/fixtures.html
tests/test_api.js
tests/test_superwidget.js

Omits the "Authorization" header from requests where we don't have an auth key yet (i.e., when we're getting a client token for the first time).
Previously, if there was no client token available, we were sending this header: `Authorization ClientToken undefined`.
On the API side when we check for authorization headers, it's ok if the ClientToken is omitted, but we reject invalid client tokens. So `undefined` gets parsed as an invalid client token and the request is rejected :(
This came up because we added a decorator to one of our `api.before_request` functions. The decorator started checking this `undefined` client token and rejecting request before we have a chance to generate a valid one in the view.
The related API code is in [this …

Auth headers

---

demo_widget.html
src/dev/modules/model.js

Fixes the email sending functionality of the widget.
First we will reproduce the error, then we will fix it.
pull the master version of the superwidget code. `git pull origin master`
run `gulp build --local=false; echo \"Starting server at localhost:8080\"; python3 -m http.server 8080;`
open an incognito window in chrome and type in an email to send. You should get an email configuration error.
This error was the result of passing the options ID to the YesGraph API incorrectly, resulting in the YesGraph API using a set of superwidget options that do not have email sending configured.
Now we're going to test the fix.
switch branches `git checkout -B team_invite_fix`
pull the new branch `git pull origin team_invite_fix`
You also must be running the YesGraph API locally, with the new …

Send-email-invites fix

---

src/dev/modules/api.js
src/dev/modules/controller.js
tests/test_api.js
tests/test_superwidget.js

Previously, it would parse the first subdomain and then ignore the rest. For example, email@domain.co.uk would become email@domain.co
The `install` method is called by our script, and `setOptions` should normally be called later. however, if the browser is slow to load our script, then `setOptions` may sometimes run first. For example:
```html
<script src="//cdn.yesgraph.com/yesgraph-invites.min.js"></script>
<script>
// Occasionally, this method will run before the `install` method is called in the file above
YesGraphAPI.setOptions({ auth: { clientKey: "abc123" } });
</script>
```
Start by reviewing the email regex bugfix in [src/dev/modules/controller.js](https://github.com/YesGraph/yesgraph-superwidget/pull/52/files#diff-8c035b00ddc819ddafb4a3c31fc1ed1b). If you'd like to see a …

Email subdomains
